# Generated by Django 4.2.16 on 2024-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rise_user_id',
            field=models.IntegerField(default=0, help_text='RiseApp user ID'),
            preserve_default=False,
        ),
    ]
