# Generated by Django 4.2.16 on 2024-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rise_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rise_user_id',
            field=models.IntegerField(blank=True, help_text='RiseApp user ID', null=True),
        ),
    ]
