# Generated by Django 4.2.16 on 2024-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_rise_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jira_email_address',
            field=models.EmailField(blank=True, help_text='Jira Email Address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rise_user_id',
            field=models.IntegerField(blank=True, help_text='RiseApp User ID', null=True),
        ),
    ]
