# Generated by Django 4.2.16 on 2024-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_jira_email_address_alter_user_rise_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jira_url',
            field=models.URLField(blank=True, help_text='e.g. https://testing.atlassian.net', max_length=255, null=True),
        ),
    ]
