# Generated by Django 4.2.16 on 2024-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_jira_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jira_api_key',
            field=models.TextField(blank=True, help_text='Jira API Key', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rise_api_key',
            field=models.TextField(blank=True, help_text='RiseApp API Key', null=True),
        ),
    ]
