# Generated by Django 4.2.16 on 2024-09-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_jira_api_key_alter_user_rise_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Account'},
        ),
    ]
