# Generated by Django 4.2 on 2024-09-10 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-date_created'],
                'unique_together': {('user', 'date_created')},
            },
        ),
        migrations.CreateModel(
            name='RiseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('rise_entry_id', models.CharField(max_length=20)),
                ('rise_assignment_id', models.CharField(max_length=20)),
                ('rise_assignment_name', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='entries.entry')),
            ],
        ),
        migrations.CreateModel(
            name='JiraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_issue_number', models.CharField(max_length=255)),
                ('minutes_spent', models.IntegerField()),
                ('description', models.TextField()),
                ('jira_entry_id', models.CharField(max_length=20)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entries.entry')),
            ],
            options={
                'verbose_name_plural': 'Jira Entries',
                'unique_together': {('entry', 'jira_issue_number')},
            },
        ),
    ]
