# Generated by Django 4.2.16 on 2024-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riseentry',
            name='log_type',
            field=models.CharField(default='assignment', max_length=200),
        ),
    ]
