# Generated by Django 4.2 on 2024-09-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.CreateModel(
            name='RiseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('rise_entry_id', models.CharField(max_length=20)),
                ('synced', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entries.entry')),
            ],
        ),
        migrations.CreateModel(
            name='JiraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_issue_number', models.CharField(max_length=255)),
                ('minutes_spent', models.IntegerField()),
                ('description', models.TextField()),
                ('jira_entry_id', models.CharField(max_length=20)),
                ('synced', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entries.entry')),
            ],
            options={
                'unique_together': {('entry', 'jira_issue_number')},
            },
        ),
    ]
