# Generated by Django 4.2.16 on 2024-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_riseentry_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='riseentry',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
    ]
