# Generated by Django 4.2.16 on 2024-09-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_riseentry_hours_worked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_created'], 'verbose_name': 'Timesheet Entry', 'verbose_name_plural': 'Timesheet Entries'},
        ),
    ]
