# Generated by Django 4.2 on 2024-09-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jiraentry',
            options={'verbose_name_plural': 'Jira Entries'},
        ),
        migrations.AlterField(
            model_name='riseentry',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='entries.entry'),
        ),
    ]
